### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by alexmougios** [achertovsky/paypal-yii2#1]
i get 404 error on every action. how this module works? any more info?

**Comment by achertovsky** [comment]
@alexmougios 
Please, explain more what you doing and what happening. Any code examples mb.

**Comment by alexmougios** [comment]
I Installed your module in a yii2 basic 2.0.9 app. i followed your instruction and added 'payment' => [
    'class' => 'achertovsky\paypal\Module',
], in the config in modules section. But every action (payment/payment/*) it gives me a 404 error. something is wrong with my urls. i have not enabled pretty urls.

**Comment by achertovsky** [comment]
@alexmougios 
u want me to help u enable pretty urls?
in components section add

```
'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
            'class' => 'yii\web\UrlManager',
            'baseUrl' => '/',
        ],
```

and make sure that 
your components => request have "baseUrl" => ""

ex:

```
$config = [
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'ZRBJoKne45n76lNqrNxPvEgg3RDSYudY',
            'baseUrl' => '',
        ],
    ],
];
```

**Comment by alexmougios** [comment]
now i don't want to enable pretty urls at the moment, my problem is than when i use Url::toRoute(payment/payment/pay) i get a 404 error not found!

**Comment by alexmougios** [comment]
And how can i use backend/config in yin base app? should i overwrite controller and view?

**Comment by achertovsky** [comment]
@alexmougios 
first redirect must look like `Url::toRoute(['/payment/payment/pay'])`  
and to use it in base app - yes, you should override module backend controller and views in new place

**Comment by alexmougios** [comment]
ok thanks a lot i will try it and i'll inform you!

**Comment by alexmougios** [comment]
Hi  i tried everything but still 404 error. i Ended up overwriting fronted and backend controllers to app/controllers/ and is working find! thanks a lot for your help!!! Great work!
