### ISSUE TITLE
Getting currency error (paypal related)

### ISSUE THREAD

**Issue by arizanovj** [achertovsky/paypal-yii2#2]
Hi. Do you plan to update the paypal merchant sdk requirement, it's pretty old. I am getting an error that I think is related to that. Have you tried using it with other currencies other than USD ?
When I use USD everything is ok, but as soon as I change the currency I get this error:

```
array (
  0 => 
  ErrorType::__set_state(array(
     'ShortMessage' => 'Transaction refused because of an invalid argument. See additional error messages for details.',
     'LongMessage' => 'The transaction currency specified must be the same as previously specified.',
     'ErrorCode' => '10444',
     'SeverityCode' => 'Error',
     'ErrorParameters' => NULL,
  )),
)
```

Thanks.

**Comment by achertovsky** [comment]
@arizanovj 
in current library i never used another currencies, but before i had experience with it and everything was successfull. can you provide me example of your code? i will try to help

**Comment by arizanovj** [comment]
I got it working, The thing was I needed to override the default currency in the module class (which is USD). Now is working fine so we can close the issue. 
On other topic (not sure if I should ask it on this issue), do you have plans to implement the ipnListener action ? I'll need it so I might implement it myself. 
Thanks for your work.

**Comment by achertovsky** [comment]
@arizanovj 
yes, i have plans to implement IPN for subscriptions. currently status can be achieved by hand checking.
in future ipn will replace it.

you welcome. i glad that my module useful :)
