### ISSUE TITLE
Can't use module

### ISSUE THREAD

**Issue by ANulikJan** [achertovsky/paypal-yii2#3]
Hi there, I have installed this module, but don't know how to use it.
I have read the instruction, but the url '/payment/payment/subscription-express-create' gives me 404, where it should go, what it should open?
How can I use this module in my project, where I have few plans and users must subscribe them to use our services. Subscribe will be done after successfully payment in Paypal.
I have form in my view, so where I should redirect the user after paypal button click, using module?

**Comment by achertovsky** [comment]
@ANulikJan please, attach below code listings of your implementation

**Comment by ANulikJan** [comment]
I have put this on my controller where my form action goes.

>  public function actionPay(){
>         $numericValue = 15;
> //or
>         $numericValue = 15.2;
> 
>         $subscription = new PaypalSubscriptionExpress();
>         $subscription->setScenario('prepare');
>         $subscription->setAttributes([
>             'user_id' => 1,
>             'price' => $numericValue,
>             'currency' => Yii::$app->getModule('payment')->currency,
>             'period' => 30,
>             'description' => 'This is description flow from module wiki'
>         ]);
>         $subscription->save();
>         return $this->redirect(Url::toRoute(['/payment/payment/subscription-express-create', 'price' => $numericValue, 'modelId' => $subscription->id]));
> 
>     }

this is my main.php

> 'modules' => [
>         'payment' => 'achertovsky\paypal\Module'
>     ],

I don't know what to do next.

**Comment by achertovsky** [comment]
@ANulikJan 
what happens when you doing (via browser) `*yourdomain*/*yourcontroller*/pay` ??

**Comment by ANulikJan** [comment]
It redurect to '/payment/payment/subscription-express-create' and get 404 
![screenshot from 2017-09-20 15-01-52](https://user-images.githubusercontent.com/4806435/30640623-ac974238-9e14-11e7-91e1-b4ba4aaa08b0.png)

**Comment by ANulikJan** [comment]
Url is not correct. What should I do, maybe put something in urlmanager, I just can't understand how to use module, as there is no examples and not enough documentation. 
It seams inserted values to db in subscribe table.
Can you help me please?

**Comment by achertovsky** [comment]
@ANulikJan 
i checked code for you and for 404 can be 3 reasons:
- You disabled subscription express (which i dont see in your config)
- You have validation error on creating subscription
- Module have exception in code flow

can you check `/debug` for current actions?

**Comment by ANulikJan** [comment]
subscription express is enabled, as I understand it should be on Module.php file 
```
//boolean which indicates is subscription flow is enabled in app
    public $enableSubscriptionExpress = true;
```
I don't thing there is any exception and error in my controller, as data is inserting in db.
/debug 
![screenshot from 2017-09-20 15-22-42](https://user-images.githubusercontent.com/4806435/30641296-92fcd8d0-9e17-11e7-8c3d-473ff8fac810.png)

**Comment by achertovsky** [comment]
@ANulikJan 
i see that it builds links in weird way:
`frontend/web/payment/frontend/payment/subscription-express-create`

**Comment by ANulikJan** [comment]
I have type that url by myself, by hand

**Comment by achertovsky** [comment]
@ANulikJan 
can you check db and say for sure that there IS model with id 3? 
and please attach screenshot of logs from `subscribe/pay`

**Comment by ANulikJan** [comment]
data that I have in DB
![screenshot from 2017-09-20 15-29-41](https://user-images.githubusercontent.com/4806435/30641556-ad99044c-9e18-11e7-814d-c9e00f17331c.png)
![screenshot from 2017-09-20 15-29-58](https://user-images.githubusercontent.com/4806435/30641555-ace9a3ee-9e18-11e7-9525-7fd5ce94d872.png)

subscribe/pay controller action
![screenshot from 2017-09-20 15-31-27](https://user-images.githubusercontent.com/4806435/30641585-d522cb06-9e18-11e7-8aad-bc05a5fc19b0.png)

form paypal
![screenshot from 2017-09-20 15-32-30](https://user-images.githubusercontent.com/4806435/30641625-f7fc13c6-9e18-11e7-9f5f-678e92f60661.png)

**Comment by achertovsky** [comment]
@ANulikJan 
i tested few things for you.
So, currently u not using pretty urls so you have to format your url to be like `localhost/g-connector/frontend/web/index.php?r=payment/payment/subscription-express-create&price=15.2&modelId=3`
How to make such URL's via Url::toRoute - i dont know, sorry
but i know how to make your project use links like
`localhost/g-connector/payment/payment/subscription-express-create?price=15.2&modelId=3`

to get it you have to configure your UrlManager in next way
```
    'components' => [
        'urlManager' => [
            'class' => 'yii\web\UrlManager',
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'baseUrl' => '/',
        ],
    ],
```

**Comment by achertovsky** [comment]
@ANulikJan 
updated prev comment

**Comment by achertovsky** [comment]
@ANulikJan 
any progress?

p.s. without response i will close this issue in a while

**Comment by Sensetivity** [comment]
I have same issue.
How to use this module?

I put 
```
        'payment' => [
            'class' => 'achertovsky\paypal\Module',
        ],
```

Into my web.php file but when I go http://domain.dev/payment/ I got 404 error.
http://domain.dev/payment/frontend
http://domain.dev/payment/frontend/payment

I also got 404 error.

**Comment by Sensetivity** [comment]
Okay it fixed by adding controller map
```
    'modules' => [
.....................
        'payment' => [
            'class' => 'achertovsky\paypal\Module',
            'controllerMap' => [
                'payment' => 'achertovsky\paypal\controllers\frontend\PaymentController',
                'payment-admin' => 'achertovsky\paypal\controllers\backend\PaymentController',
            ],
        ],
...................
    ],
```
